DROP TABLE IF EXISTS pokemons           CASCADE;

create table pokemons (   --ACTIVERECORD LOOKS FOR TABLENAME THAT IS A PLURAL OF CLASSNAME OR SOMETHING OR OTHER THING-Y
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  cp VARCHAR(255),
  poke_type VARCHAR(255),
  img_url VARCHAR(255)
);
